### ISSUE TITLE
> **Do you want to request a _feature_ or report a _bug_?**

### ISSUE THREAD

**Issue by lubas569** [yarnpkg/pnp-sample-app#11]
> **Do you want to request a _feature_ or report a _bug_?**
> 
> **What is the current behavior?**
> 
> **If the current behavior is a bug, please provide the steps to reproduce.**
> 
> **What is the expected behavior?**
> 
> **Please mention your node.js, yarn and operating system version.**

_Originally posted by @lubas569 in https://github.com/yarnpkg/yarn/issues/7695#issuecomment-554721814_

**Comment by arcanis** [comment]
?
